* Согласованность
** Объединение групповых и индивидуальных целей, а также направления деятельности, на основе одного представления об организации.
*** Наши приоритеты соответствуют бизнес целям :Культура:
*** Мы предпочитаем добровольно браться за задачи, а не ждать пока нам их назначат :Культура:
*** У нашей команды есть четкие цели, которые соответствуют видению компании :Культура:Измерения:
*** Наша продуктовая команда ориентируется на поддержание устойчивой скорости работы, меньше концентрируясь на текущей скорости :Культура:Автоматизация:Измерения:
*** Мы концентрируем свое внимание на времени, требуемом для починки, а не на времени между инцидентами :Культура:Измерения: 
*** DevOps не ограничивается какой-то определенной ролью в нашей организации :Культура:
*** DevOps не ограничивается какой-то определенной командой в нашей организации :Культура:
*** Наши производственные функции рассматриваются в качестве источника конкурентного преимущества. :Культура:
* Контекст
** Делая необходимую информацию и список контактов доступными для тех, кому это требуется и когда это требуется.
*** Представители нашей команды эксплуатации принимают участие в планировании спринтов для разработки. :Культура:Шэринг:
*** Мы делаем потенциальные изменения видимыми для всех членов нашей продуктовой команды. :Культура:Шэринг:
*** У нас имеется автоматизированная система запуска задач и настроена возможность получения нотификаций об их статусе в наш командный чат. :Культура:Шэринг:
*** Мы регулярно консультируемся с аудиторами и органами регулирования, и просим наставлений при проектировании систем. :Культура:Шэринг:
*** Обсуждение задач и их приоритетов является обычной практикой в нашей команде :Культура:Шэринг:
*** У нас имеется централизованная система отправки мгновенных сообщений всем членам нашей продуктовой команды. :Шэринг:
*** Все члены нашей продуктовой команды имеют доступ к информации о статусе окружения, метриках и истории. :Шэринг:Измерения:
*** Все члены нашей продуктовой команды имеют доступ к информации о статусе кода, метриках и истории. :Шэринг:Измерения:
* Обучение
** Предоставление возможностей личностного роста и стимулирование понимания через процесс постоянного совершенствования.
*** Мы культивируем среду непрерывного обучения. :Культура:
*** Мы регулярно отмечаем успехи и новые знания, полученные нашей продуктовой командой. :Культура:
*** Мы регулярно делимся полученными знаниями и успехами нашей продуктовой команды с остальной частью организации. :Культура:Шэринг:
*** Мы открыто обсуждаем провалы и неудачи, чтобы поделиться опытом с другими. :Культура:Шэринг:Измерения:
*** Мы выявляем навыки, необходимые для совершенствования и достижения будущих целей. :Культура:Измерения:
*** Мы стремимся проводить анализ того, как мы выполняем нашу работу и как эффективно мы это делаем. :Культура:Измерения:
*** Наши прогнозы основаны на измерениях и прошлом опыте :Измерения:
* Жизненный цикл
** Отношение к ПО как к продукту, заслуживающему заботы, внимания и размышлений в рамках постоянно меняющейся экосистемы.
*** Цикл разработки нашего ПО равен 2 неделям или меньше. :Культура:
*** Цикл разработки нашего ПО определяется релизом рабочего изменения в продакшн. :Культура:Измерения:
*** Мы приостанавливаем разработку при обнаружении неисправности и ставим в качестве приоритета её устранение. :Культура:
*** Разработчики или владельцы продуктов могут производить деплой нашего продукта в продакшн. :Культура:Автоматизация:
*** Мы автоматизировали тестирование до того, как автоматизировали деплой в продакшн. :Автоматизация:Тестирование:
*** Наш процесс настройки конфигурации систем автоматизирован. :Автоматизация:
*** Конфигурация задеплоенной системы неизменна. :Автоматизация:
*** Автоматизация релиза и деплоя не имеет привязки к окружению. :Автоматизация:Тестирование:
* Организация
** Создание структуры, обеспечивающей взаимодействие и сплоченность, которая позволит поддерживать сотрудничество и продуктивность работы. 
*** Наша экспертиза в предметной области не ограничивается несколькими людьми. :Культура:Шэринг:
*** Мы даем возможность равноправного и кросс-функционального анализа изменений :Культура:Шэринг:Тестирование:
*** Наша организация выстроена вокруг кросс-функциональных команд. :Культура:
*** Наши команды являются клиент и продукт-ориентированными. :Культура:
*** Мы пересматриваем приоритеты на регулярной основе. :Культура:Шэринг:
*** Наши разработчики имеют доступ к системам, аналогичным производственным, для работы и тестирования. :Автоматизация:Тестирование:
*** Наши разработчики имеют доступ к данным, аналогичным производственным, для работы и тестирования. :Автоматизация:Тестирование:
*** Наши разработчики имеют доступ к зависимостям, требуемым для сборки и тестирования ПО. :Автоматизация:Тестирование:
* Процесс
** Ритуалы, направленные на воспитание уверенности и системности, тем самым обеспечивающие основу для постоянного совершенствования. 
*** Наша организация использует Agile-практики. :Культура:
*** Мы практикуем разбор и анализ инцидентов без обвинения кого-либо за совершенные ошибки. :Культура:Шэринг:
*** Мы регулярно рассматриваем существующие ограничения в нашем процессе доставки. :Культура:
*** Наша конфигурация хранится в системе управления версиями. :Автоматизация:Тестирование:
*** Наша документация версионируется и доступна всем :Шэринг:
*** Мы поддерживаем список накопившихся задач, который виден всем членам команды и доступен для комментариев. :Шэринг:
*** Наша разработка основана на TDD (test-driven development) или BDD (behaviour-driven development) :Тестирование:
*** Мы тестируем изменения перед слиянием в основную ветку. :Тестирование:
*** Мы проверяем наши изменения нагрузочным тестированием на основе реальных данных и шаблонов использования. :Тестирование:
